[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."fundos"]
  timeout = 26

[functions."fundos-historico"]
  timeout = 26

[[redirects]]
  from = "/api/tesouro"
  to = "/.netlify/functions/tesouro"
  status = 200

[[redirects]]
  from = "/api/bcb"
  to = "/.netlify/functions/bcb"
  status = 200

[[redirects]]
  from = "/api/fundos"
  to = "/.netlify/functions/fundos"
  status = 200

[[redirects]]
  from = "/api/mundo"
  to = "/.netlify/functions/mundo"
  status = 200

[[redirects]]
  from = "/api/hot-movers"
  to = "/.netlify/functions/hot-movers"
  status = 200

[[redirects]]
  from = "/api/cotacoes"
  to = "/.netlify/functions/cotacoes"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/fundos-historico"
  to = "/.netlify/functions/fundos-historico"
  status = 200

[[redirects]]
  from = "/api/inflacao"
  to = "/.netlify/functions/inflacao"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/config.json"
  status = 200
